export const category = [
    {
        id: 1,
        name: "Karan Vaidya",
        image: '',
        icon:'/tooth.png',
        description: 'Dentist',
        rating: 4.5,
    },
    {
        id: 2,
        name: "Rahul",
        image: '',
        icon:'/cardio.png',
        description: 'Cardiologist',
        rating: 4.5,
    },
    {
        id: 3,
        name: "Krishna",
        image: '',
        icon:'/osteology.png',
        description: 'Orthopedic',
        rating: 4.5,
    },    
    {
        id: 4,
        name: "Karthik",
        image: '',
        icon:'/neurologist.png',
        description: 'Neurologist',
        rating: 4.5,
    },    
    {
        id: 5,
        name: "Rethi",
        image: '',
        icon:'/otolgy.png',
        description: 'Otology',
        rating: 4.5,
    },    
    {
        id: 6,
        name: "Harsha",
        image: '',
        icon:'/physician.png',
        description: 'Physician',
        rating: 4.5,
    },    
    {
        id: 7,
        name: "Payal",
        image: '',
        icon:'/surgeon.png',
        description: 'Surgeon',
        rating: 4.5,
    },    
    {
        id: 8,
        name: "Gauthami",
        image: '',
        icon:'/psychotropic.png',
        description: 'Psychotropic',
        rating: 4.5,
    },    
    {
        id: 9,
        name: "Lipika",
        image: '',
        icon:'/eye.png',
        description: 'Eye Specialist',
        rating: 4.5,
    },
]