export const doctors = [
    {
      id: 1,
      name: "Dr. Ramesh Sharma",
      address: 'Kankanady',
      patients: '2000+',
      experience: '15 years',
      speciality: "Cardiologist",
      image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824610/doc5_wmgpzr.jpg",
      about: 'Expert in heart diseases and surgeries.',
      time: '9:00 AM - 5:00 PM',
      phone: '555-1234',
      premium: true
    },
    {
      id: 2,
      name: "Dr. Sushma PS",
      address: 'Balmatta',
      patients: '1500+',
      experience: '10 years',
      speciality: "Dentist",
      image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824609/doc3_bpo3av.jpg",
      about: 'Specializes in cosmetic and pediatric dentistry.',
      time: '8:00 AM - 4:00 PM',
      phone: '555-5678',
      premium: true
    },
    {
      id: 3,
      name: "Dr. Ajith",
      address: 'Puttur',
      patients: '1800+',
      experience: '12 years',
      speciality: "Orthopedic",
      image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824609/doc4_pav05o.jpg",
      about: 'Focuses on joint replacement and sports injuries.',
      time: '10:00 AM - 6:00 PM',
      phone: '555-9101',
      premium: true
    },
    {
      id: 4,
      name: "Dr. Narayan",
      address: 'Attavar',
      patients: '2200+',
      experience: '20 years',
      speciality: "Neurologist",
      image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824610/doc1_mtudvx.jpg",
      about: 'Expert in neurological disorders and brain surgeries.',
      time: '9:00 AM - 5:00 PM',
      phone: '555-1112',
      premium: true
    },
    {
      id: 5,
      name: "Dr. Pradeep",
      address: 'Nandigudda',
      patients: '1400+',
      experience: '8 years',
      speciality: "Otology",
      image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824610/doc6_nhq8yz.jpg",
      about: 'Specialist in ear disorders and hearing loss.',
      time: '8:00 AM - 4:00 PM',
      phone: '555-1314',
      premium: true
    },
    {
      id: 6,
      name: "Dr. Vasant",
      address: 'Bejai',
      patients: '2500+',
      experience: '18 years',
      speciality: "Physician",
      image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824610/doc7_rbiowd.jpg",
      about: 'General physician with expertise in chronic diseases.',
      time: '10:00 AM - 6:00 PM',
      phone: '555-1516',
      premium: true
    },
    {
      id: 7,
      name: "Dr. Varsha",
      address: 'Suratkal',
      patients: '1600+',
      experience: '14 years',
      speciality: "Surgeon",
      image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824610/doc5_yrp7td.webp",
      about: 'Performs complex surgeries with a high success rate.',
      time: '9:00 AM - 5:00 PM',
      phone: '555-1718',
      premium: true
    },
    {
      id: 8,
      name: "Dr. Sumeet",
      address: 'Udupi',
      patients: '1300+',
      experience: '9 years',
      speciality: "Psychotropic",
      image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824610/doc8_c6nfm5.jpg",
      about: 'Specializes in mental health and psychiatric care.',
      time: '8:00 AM - 4:00 PM',
      phone: '555-1920',
      premium: true
    },
    {
      id: 9,
      name: "Dr. Johnny",
      address: 'Kadro',
      patients: '1700+',
      experience: '11 years',
      speciality: "Eye Specialist",
      image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824610/doc9_lfp84v.webp",
      about: 'Expert in eye care and vision correction.',
      time: '10:00 AM - 6:00 PM',
      phone: '555-2122',
      premium: true
    }
  ];
  
