export const doctors = [
  {
    id: 1,
    name: "Dr. Ramesh Sharma",
    address: "Kankanady",
    patients: "2000+",
    experience: "15 years",
    speciality: "Cardiologist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824610/doc5_wmgpzr.jpg",
    about: "Expert in heart diseases and surgeries.",
    time: "9:00 AM - 5:00 PM",
    phone: "555-1234",
    premium: true
  },
  {
    id: 2,
    name: "Dr. Sushma PS",
    address: "Balmatta",
    patients: "1500+",
    experience: "10 years",
    speciality: "Dentist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824609/doc3_bpo3av.jpg",
    about: "Specializes in cosmetic and pediatric dentistry.",
    time: "8:00 AM - 4:00 PM",
    phone: "555-5678",
    premium: true
  },
  {
    id: 3,
    name: "Dr. Ajith",
    address: "Puttur",
    patients: "1800+",
    experience: "12 years",
    speciality: "Orthopedic",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824609/doc4_pav05o.jpg",
    about: "Focuses on joint replacement and sports injuries.",
    time: "10:00 AM - 6:00 PM",
    phone: "555-9101",
    premium: true
  },
  {
    id: 4,
    name: "Dr. Narayan",
    address: "Attavar",
    patients: "2200+",
    experience: "20 years",
    speciality: "Neurologist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824610/doc1_mtudvx.jpg",
    about: "Expert in neurological disorders and brain surgeries.",
    time: "9:00 AM - 5:00 PM",
    phone: "555-1112",
    premium: true
  },
  {
    id: 5,
    name: "Dr. Pradeep",
    address: "Nandigudda",
    patients: "1400+",
    experience: "8 years",
    speciality: "Otology",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824610/doc6_nhq8yz.jpg",
    about: "Specialist in ear disorders and hearing loss.",
    time: "8:00 AM - 4:00 PM",
    phone: "555-1314",
    premium: true
  },
  {
    id: 6,
    name: "Dr. Vasant",
    address: "Bejai",
    patients: "2500+",
    experience: "18 years",
    speciality: "Physician",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824610/doc7_rbiowd.jpg",
    about: "General physician with expertise in chronic diseases.",
    time: "10:00 AM - 6:00 PM",
    phone: "555-1516",
    premium: true
  },
  {
    id: 7,
    name: "Dr. Varsha",
    address: "Suratkal",
    patients: "1600+",
    experience: "14 years",
    speciality: "Surgeon",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824610/doc5_yrp7td.webp",
    about: "Performs complex surgeries with a high success rate.",
    time: "9:00 AM - 5:00 PM",
    phone: "555-1718",
    premium: true
  },
  {
    id: 8,
    name: "Dr. Sumeet",
    address: "Udupi",
    patients: "1300+",
    experience: "9 years",
    speciality: "Psychotropic",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824610/doc8_c6nfm5.jpg",
    about: "Specializes in mental health and psychiatric care.",
    time: "8:00 AM - 4:00 PM",
    phone: "555-1920",
    premium: true
  },
  {
    id: 9,
    name: "Dr. Johnny",
    address: "Kadro",
    patients: "1700+",
    experience: "11 years",
    speciality: "Eye Specialist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1719824610/doc9_lfp84v.webp",
    about: "Expert in eye care and vision correction.",
    time: "10:00 AM - 6:00 PM",
    phone: "555-2122",
    premium: true
  },
  {
    id: 10,
    name: "Dr. Ravi Kumar",
    address: "Bendoor",
    patients: "2100+",
    experience: "17 years",
    speciality: "Cardiologist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076709/doc12_a4rqpg.jpg",
    about: "Specializes in cardiovascular treatments.",
    time: "9:00 AM - 5:00 PM",
    phone: "555-2223",
    premium: false
  },
  {
    id: 11,
    name: "Dr. Neha Singh",
    address: "Falnir",
    patients: "1600+",
    experience: "11 years",
    speciality: "Dentist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076709/doc24_kaxagi.jpg",
    about: "Expert in orthodontics and cosmetic dentistry.",
    time: "8:00 AM - 4:00 PM",
    phone: "555-2345",
    premium: true
  },
  {
    id: 12,
    name: "Dr. Arvind Rao",
    address: "Hampankatta",
    patients: "1900+",
    experience: "13 years",
    speciality: "Orthopedic",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076709/doc14_c5ukdh.jpg",
    about: "Specializes in sports injuries and rehabilitation.",
    time: "10:00 AM - 6:00 PM",
    phone: "555-3456",
    premium: false
  },
  {
    id: 13,
    name: "Dr. Lakshmesh Bhat",
    address: "Kavoor",
    patients: "2000+",
    experience: "18 years",
    speciality: "Neurologist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076711/doc15_uvsomb.jpg",
    about: "Focuses on epilepsy and movement disorders.",
    time: "9:00 AM - 5:00 PM",
    phone: "555-4567",
    premium: true
  },
  {
    id: 14,
    name: "Dr. Shanthi Kulkarni",
    address: "Derebail",
    patients: "1700+",
    experience: "9 years",
    speciality: "Otology",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076712/doc25_d06tgi.jpg",
    about: "Specializes in hearing aids and ear infections.",
    time: "8:00 AM - 4:00 PM",
    phone: "555-5678",
    premium: false
  },
  {
    id: 15,
    name: "Dr. Manisha Reddy",
    address: "Urwa",
    patients: "2200+",
    experience: "20 years",
    speciality: "Physician",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076713/doc17_bwaycs.jpg",
    about: "Experienced in treating chronic illnesses.",
    time: "10:00 AM - 6:00 PM",
    phone: "555-6789",
    premium: true
  },
  {
    id: 16,
    name: "Dr. Rahul Desai",
    address: "Bondel",
    patients: "1300+",
    experience: "7 years",
    speciality: "Surgeon",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076716/doc19_we2y3a.jpg",
    about: "Performs minimally invasive surgeries.",
    time: "9:00 AM - 5:00 PM",
    phone: "555-7890",
    premium: false
  },
  {
    id: 17,
    name: "Dr. Sneha Patil",
    address: "Kuloor",
    patients: "1400+",
    experience: "8 years",
    speciality: "Psychotropic",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076714/doc16_uw1tsm.jpg",
    about: "Focuses on adolescent mental health.",
    time: "8:00 AM - 4:00 PM",
    phone: "555-8901",
    premium: true
  },
  {
    id: 18,
    name: "Dr. Ravi Hegde",
    address: "Surathkal",
    patients: "1900+",
    experience: "14 years",
    speciality: "Eye Specialist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076719/doc20_jh9fec.jpg",
    about: "Specializes in cataract and refractive surgery.",
    time: "10:00 AM - 6:00 PM",
    phone: "555-9012",
    premium: false
  },
  {
    id: 19,
    name: "Dr. Vishal Kumar",
    address: "Kottara",
    patients: "2000+",
    experience: "16 years",
    speciality: "Cardiologist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076719/doc10_vuqe2i.jpg",
    about: "Expert in interventional cardiology.",
    time: "9:00 AM - 5:00 PM",
    phone: "555-0123",
    premium: true
  },
  {
    id: 20,
    name: "Dr. Priya Naik",
    address: "Kudroli",
    patients: "1800+",
    experience: "12 years",
    speciality: "Dentist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076716/doc18_rpojge.jpg",
    about: "Specializes in endodontics and oral surgery.",
    time: "8:00 AM - 4:00 PM",
    phone: "555-2345",
    premium: false
  },
  {
    id: 21,
    name: "Dr. Suresh Poojary",
    address: "Ashoknagar",
    patients: "1600+",
    experience: "10 years",
    speciality: "Orthopedic",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076720/doc21_l1jwoe.jpg",
    about: "Expert in spine surgeries and fracture management.",
    time: "10:00 AM - 6:00 PM",
    phone: "555-3456",
    premium: true
  },
  {
    id: 22,
    name: "Dr. Mehnat Rao",
    address: "Bendoorwell",
    patients: "2200+",
    experience: "21 years",
    speciality: "Neurologist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076721/doc13_swhgp6.jpg",
    about: "Specializes in stroke and neurorehabilitation.",
    time: "9:00 AM - 5:00 PM",
    phone: "555-4567",
    premium: false
  },
  {
    id: 23,
    name: "Dr. Mahesh Shetty",
    address: "Jeppu",
    patients: "1400+",
    experience: "8 years",
    speciality: "Otology",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076722/doc11_eoqzze.jpg",
    about: "Focuses on cochlear implants and vertigo.",
    time: "8:00 AM - 4:00 PM",
    phone: "555-5678",
    premium: true
  },
  {
    id: 24,
    name: "Dr. Sandhya Kini",
    address: "Kodialbail",
    patients: "1700+",
    experience: "11 years",
    speciality: "Physician",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076722/doc28_pzssnf.jpg",
    about: "Expert in internal medicine and diabetes care.",
    time: "10:00 AM - 6:00 PM",
    phone: "555-6789",
    premium: false
  },
  {
    id: 25,
    name: "Dr. Anil Pai",
    address: "Kottara Chowki",
    patients: "2100+",
    experience: "19 years",
    speciality: "Surgeon",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076723/doc31_nnjavb.jpg",
    about: "Specializes in laparoscopic and bariatric surgery.",
    time: "9:00 AM - 5:00 PM",
    phone: "555-7890",
    premium: true
  },
  {
    id: 26,
    name: "Dr. Shruti Nayak",
    address: "Bikarnakatte",
    patients: "1200+",
    experience: "7 years",
    speciality: "Psychotropic",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076723/doc30_txsinh.jpg",
    about: "Specializes in child and adolescent psychiatry.",
    time: "8:00 AM - 4:00 PM",
    phone: "555-8901",
    premium: false
  },
  {
    id: 27,
    name: "Dr. Shailesh Kumar",
    address: "Panambur",
    patients: "1500+",
    experience: "5 years",
    speciality: "Eye Specialist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076723/doc29_xbefex.jpg",
    about: "Expert in glaucoma and retinal disorders.",
    time: "10:00 AM - 6:00 PM",
    phone: "555-9012",
    premium: true
  },
  {
    id: 28,
    name: "Dr. Rakesh Jain",
    address: "Yeyyadi",
    patients: "1300+",
    experience: "8 years",
    speciality: "Cardiologist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076724/doc32_gvbg4b.jpg",
    about: "Focuses on heart failure and arrhythmias.",
    time: "9:00 AM - 5:00 PM",
    phone: "555-0123",
    premium: false
  },
  {
    id: 29,
    name: "Dr. Anjana Hegde",
    address: "Ullal",
    patients: "1400+",
    experience: "9 years",
    speciality: "Dentist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076723/doc26_suidmf.jpg",
    about: "Expert in pediatric dentistry and orthodontics.",
    time: "8:00 AM - 4:00 PM",
    phone: "555-2345",
    premium: true
  },
  {
    id: 30,
    name: "Dr. Girish Bhat",
    address: "Vamanjoor",
    patients: "2000+",
    experience: "15 years",
    speciality: "Orthopedic",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076726/doc22_ajtmmv.jpg",
    about: "Specializes in trauma and joint replacement.",
    time: "10:00 AM - 6:00 PM",
    phone: "555-3456",
    premium: false
  },
  {
    id: 31,
    name: "Dr. Harish Shetty",
    address: "Thokkottu",
    patients: "2300+",
    experience: "20 years",
    speciality: "Neurologist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076726/doc23_k8fct4.jpg",
    about: "Focuses on epilepsy and multiple sclerosis.",
    time: "9:00 AM - 5:00 PM",
    phone: "555-4567",
    premium: true
  },
  {
    id: 32,
    name: "Dr. Uma Rao",
    address: "Pavoor",
    patients: "1500+",
    experience: "11 years",
    speciality: "Otology",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720076724/doc27_pkjw0n.jpg",
    about: "Specializes in ear infections and balance disorders.",
    time: "8:00 AM - 4:00 PM",
    phone: "555-5678",
    premium: false
  },
  {
    id: 33,
    name: "Dr. Raghavendra Acharya",
    address: "Nagori",
    patients: "1700+",
    experience: "12 years",
    speciality: "Physician",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720077631/doc33_mrftdk.jpg",
    about: "Expert in infectious diseases and general health.",
    time: "10:00 AM - 6:00 PM",
    phone: "555-6789",
    premium: true
  },
  {
    id: 34,
    name: "Dr. Seema Jain",
    address: "Shaktinagar",
    patients: "2000+",
    experience: "17 years",
    speciality: "Surgeon",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720077625/doc37_t7imun.jpg",
    about: "Performs advanced robotic surgeries.",
    time: "9:00 AM - 5:00 PM",
    phone: "555-7890",
    premium: false
  },
  {
    id: 35,
    name: "Dr. Uday Kulkarni",
    address: "Kankanady",
    patients: "1400+",
    experience: "9 years",
    speciality: "Psychotropic",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720077625/doc38_f3wppk.jpg",
    about: "Focuses on addiction and rehabilitation.",
    time: "8:00 AM - 4:00 PM",
    phone: "555-8901",
    premium: true
  },
  {
    id: 36,
    name: "Dr. Vinutha Desai",
    address: "Bajpe",
    patients: "1600+",
    experience: "10 years",
    speciality: "Cardiologist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720077623/doc35_q51u6t.jpg",
    about: "Expert in hypertension and coronary artery disease.",
    time: "9:00 AM - 5:00 PM",
    phone: "555-9012",
    premium: false
  },
  {
    id: 37,
    name: "Dr. Lakshmi Shenoy",
    address: "Padil",
    patients: "2000+",
    experience: "14 years",
    speciality: "Dentist",
    image: "https://res.cloudinary.com/dgabitmel/image/upload/v1720077624/doc36_p8allx.jpg",
    about: "Specializes in restorative and preventive dentistry.",
    time: "10:00 AM - 6:00 PM",
    phone: "555-0123",
    premium: true
  },
];
