export const doctors = [
    {
      id: 1,
      name: "Dr. John Doe",
      address: '123 Heart St, Cardiology City',
      patients: '2000+',
      experience: '15 years',
      speciality: "Cardiologist",
      image: "/doc1.jpg",
      about: 'Expert in heart diseases and surgeries.',
      time: '9:00 AM - 5:00 PM',
      phone: '555-1234',
      premium: true
    },
    {
      id: 2,
      name: "Dr. Jane Smith",
      address: '456 Smile Ave, Dental Town',
      patients: '1500+',
      experience: '10 years',
      speciality: "Dentist",
      image: "/doc2.jpg",
      about: 'Specializes in cosmetic and pediatric dentistry.',
      time: '8:00 AM - 4:00 PM',
      phone: '555-5678',
      premium: true
    },
    {
      id: 3,
      name: "Dr. Emily Johnson",
      address: '789 Bone Blvd, Orthopedic City',
      patients: '1800+',
      experience: '12 years',
      speciality: "Orthopedic",
      image: "/doc3.jpg",
      about: 'Focuses on joint replacement and sports injuries.',
      time: '10:00 AM - 6:00 PM',
      phone: '555-9101',
      premium: true
    },
    {
      id: 4,
      name: "Dr. Michael Brown",
      address: '321 Brain Ln, Neuro Town',
      patients: '2200+',
      experience: '20 years',
      speciality: "Neurologist",
      image: "/doc4.jpg",
      about: 'Expert in neurological disorders and brain surgeries.',
      time: '9:00 AM - 5:00 PM',
      phone: '555-1112',
      premium: true
    },
    {
      id: 5,
      name: "Dr. Olivia Davis",
      address: '654 Ear St, Otology City',
      patients: '1400+',
      experience: '8 years',
      speciality: "Otology",
      image: "/doc5.jpg",
      about: 'Specialist in ear disorders and hearing loss.',
      time: '8:00 AM - 4:00 PM',
      phone: '555-1314',
      premium: true
    },
    {
      id: 6,
      name: "Dr. William Wilson",
      address: '987 Health Ave, Physician City',
      patients: '2500+',
      experience: '18 years',
      speciality: "Physician",
      image: "/doc6.jpg",
      about: 'General physician with expertise in chronic diseases.',
      time: '10:00 AM - 6:00 PM',
      phone: '555-1516',
      premium: true
    },
    {
      id: 7,
      name: "Dr. Sophia Martinez",
      address: '159 Surgery Blvd, Surgeon City',
      patients: '1600+',
      experience: '14 years',
      speciality: "Surgeon",
      image: "/doc7.jpg",
      about: 'Performs complex surgeries with a high success rate.',
      time: '9:00 AM - 5:00 PM',
      phone: '555-1718',
      premium: true
    },
    {
      id: 8,
      name: "Dr. James Anderson",
      address: '753 Mind St, Psychotropic Town',
      patients: '1300+',
      experience: '9 years',
      speciality: "Psychotropic",
      image: "/doc8.jpg",
      about: 'Specializes in mental health and psychiatric care.',
      time: '8:00 AM - 4:00 PM',
      phone: '555-1920',
      premium: true
    },
    {
      id: 9,
      name: "Dr. Ava Thompson",
      address: '852 Vision Ave, Eye City',
      patients: '1700+',
      experience: '11 years',
      speciality: "Eye Specialist",
      image: "/doc9.jpg",
      about: 'Expert in eye care and vision correction.',
      time: '10:00 AM - 6:00 PM',
      phone: '555-2122',
      premium: true
    }
  ];
  
